Player.destroy_all
Team.destroy_all

tampa = Team.create!(name:"Tampa Bay Buccaneers", champion:true, wins:17)
nuggets = Team.create!(name:"Denver Nuggets", champion:false, wins:45)
bayern = Team.create!(name:"Bayern Munich", champion:true, wins:32)
cowboys = Team.create!(name:"Dallas Cowboys", champion:false, wins:4)
dolphins = Team.create!(name:"Miami Dolphins", champion:false, wins:9)
lakers = Team.create!(name:"Los Angeles Lakers", champion:true, wins:41)

Player.create!(team_id:tampa.id, name:"Mike Evans", age:27, healthy:true)
Player.create!(team_id:tampa.id, name:"Tom Brady", age:43, healthy:true)
Player.create!(team_id:tampa.id, name:"Devin White", age:23, healthy:true)
Player.create!(team_id:tampa.id, name:"Rob Gronkowski", age:32, healthy:false)
Player.create!(team_id:nuggets.id, name:"Jamal Murray", age:24, healthy:false)
Player.create!(team_id:nuggets.id, name:"Nikola Jokic", age:26, healthy:true)
Player.create!(team_id:nuggets.id, name:"Aaron Gordan", age:25, healthy:true)
Player.create!(team_id:nuggets.id, name:"Michael Porter Jr.", age:22, healthy:true)
Player.create!(team_id:bayern.id, name:"Thomas Muller", age:31, healthy:true)
Player.create!(team_id:bayern.id, name:"Manuel Neuer", age:35, healthy:false)
Player.create!(team_id:bayern.id, name:"Bastian Schweinsteiger", age:36, healthy:false)
Player.create!(team_id:bayern.id, name:"Thiago Alcântara", age:30, healthy:true)
Player.create!(team_id:cowboys.id, name:"Dak Prescott", age:27, healthy:false)
Player.create!(team_id:cowboys.id, name:"Ezekiel Elliott", age:25, healthy:true)
Player.create!(team_id:cowboys.id, name:"Amari Cooper", age:26, healthy:true)
Player.create!(team_id:cowboys.id, name:"CeeDee Lamb", age:22, healthy:true)
Player.create!(team_id:dolphins.id, name:"Tua Tagovailoa", age:23, healthy:true)
Player.create!(team_id:dolphins.id, name:"Will Fuller", age:27, healthy:false)
Player.create!(team_id:dolphins.id, name:"Jaylen Waddle", age:22, healthy:true)
Player.create!(team_id:dolphins.id, name:"Mike Gesicki", age:25, healthy:true)
Player.create!(team_id:lakers.id, name:"LeBron James", age:36, healthy:true)
Player.create!(team_id:lakers.id, name:"Anthony Davis", age:28, healthy:true)
Player.create!(team_id:lakers.id, name:"Andre Drummond", age:27, healthy:true)
Player.create!(team_id:lakers.id, name:"Alex Caruso", age:27, healthy:true)
